package com.cp.dao;

import com.cp.model.Bicycle;

public interface BicycleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle
     *
     * @mbggenerated
     */
    int insert(Bicycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle
     *
     * @mbggenerated
     */
    int insertSelective(Bicycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle
     *
     * @mbggenerated
     */
    Bicycle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Bicycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Bicycle record);
}