package com.cp.dao;

import com.cp.model.BicycleRentalRecord;

public interface BicycleRentalRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_rental_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_rental_record
     *
     * @mbggenerated
     */
    int insert(BicycleRentalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_rental_record
     *
     * @mbggenerated
     */
    int insertSelective(BicycleRentalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_rental_record
     *
     * @mbggenerated
     */
    BicycleRentalRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_rental_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BicycleRentalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bicycle_rental_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BicycleRentalRecord record);
}