package com.cp.dao;

import com.cp.model.ModuleAssign;

public interface ModuleAssignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_assign
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_assign
     *
     * @mbggenerated
     */
    int insert(ModuleAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_assign
     *
     * @mbggenerated
     */
    int insertSelective(ModuleAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_assign
     *
     * @mbggenerated
     */
    ModuleAssign selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_assign
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ModuleAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_assign
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ModuleAssign record);
}