package com.cp.dao;

import com.cp.model.Operator;

public interface OperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated
     */
    int insert(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated
     */
    int insertSelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated
     */
    Operator selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Operator record);
}