package com.cp.dao;

import com.cp.model.HeadPortrait;

public interface HeadPortraitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head_portrait
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head_portrait
     *
     * @mbggenerated
     */
    int insert(HeadPortrait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head_portrait
     *
     * @mbggenerated
     */
    int insertSelective(HeadPortrait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head_portrait
     *
     * @mbggenerated
     */
    HeadPortrait selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head_portrait
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HeadPortrait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head_portrait
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(HeadPortrait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head_portrait
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HeadPortrait record);
}