package com.cp.model;

import java.util.Date;

public class RechargeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.account_id
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.recharge_amount
     *
     * @mbggenerated
     */
    private Integer rechargeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.recharge_time
     *
     * @mbggenerated
     */
    private Date rechargeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.id
     *
     * @return the value of recharge_record.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.id
     *
     * @param id the value for recharge_record.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.account_id
     *
     * @return the value of recharge_record.account_id
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.account_id
     *
     * @param accountId the value for recharge_record.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.recharge_amount
     *
     * @return the value of recharge_record.recharge_amount
     *
     * @mbggenerated
     */
    public Integer getRechargeAmount() {
        return rechargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.recharge_amount
     *
     * @param rechargeAmount the value for recharge_record.recharge_amount
     *
     * @mbggenerated
     */
    public void setRechargeAmount(Integer rechargeAmount) {
        this.rechargeAmount = rechargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.recharge_time
     *
     * @return the value of recharge_record.recharge_time
     *
     * @mbggenerated
     */
    public Date getRechargeTime() {
        return rechargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.recharge_time
     *
     * @param rechargeTime the value for recharge_record.recharge_time
     *
     * @mbggenerated
     */
    public void setRechargeTime(Date rechargeTime) {
        this.rechargeTime = rechargeTime;
    }
}