package com.cp.model;

public class Faculty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty.id_no
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty.faculty_no
     *
     * @mbggenerated
     */
    private String facultyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty.school_id
     *
     * @mbggenerated
     */
    private String schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty.id
     *
     * @return the value of faculty.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty.id
     *
     * @param id the value for faculty.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty.name
     *
     * @return the value of faculty.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty.name
     *
     * @param name the value for faculty.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty.id_no
     *
     * @return the value of faculty.id_no
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty.id_no
     *
     * @param idNo the value for faculty.id_no
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty.phone
     *
     * @return the value of faculty.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty.phone
     *
     * @param phone the value for faculty.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty.faculty_no
     *
     * @return the value of faculty.faculty_no
     *
     * @mbggenerated
     */
    public String getFacultyNo() {
        return facultyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty.faculty_no
     *
     * @param facultyNo the value for faculty.faculty_no
     *
     * @mbggenerated
     */
    public void setFacultyNo(String facultyNo) {
        this.facultyNo = facultyNo == null ? null : facultyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty.school_id
     *
     * @return the value of faculty.school_id
     *
     * @mbggenerated
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty.school_id
     *
     * @param schoolId the value for faculty.school_id
     *
     * @mbggenerated
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId == null ? null : schoolId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty.user_id
     *
     * @return the value of faculty.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty.user_id
     *
     * @param userId the value for faculty.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty.sex
     *
     * @return the value of faculty.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty.sex
     *
     * @param sex the value for faculty.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }
}