package com.cp.model;

import java.util.Date;

public class BicycleRentalRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_rental_record.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_rental_record.bicycle_id
     *
     * @mbggenerated
     */
    private String bicycleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_rental_record.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_rental_record.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_rental_record.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle_rental_record.consumptive_money
     *
     * @mbggenerated
     */
    private Integer consumptiveMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_rental_record.id
     *
     * @return the value of bicycle_rental_record.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_rental_record.id
     *
     * @param id the value for bicycle_rental_record.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_rental_record.bicycle_id
     *
     * @return the value of bicycle_rental_record.bicycle_id
     *
     * @mbggenerated
     */
    public String getBicycleId() {
        return bicycleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_rental_record.bicycle_id
     *
     * @param bicycleId the value for bicycle_rental_record.bicycle_id
     *
     * @mbggenerated
     */
    public void setBicycleId(String bicycleId) {
        this.bicycleId = bicycleId == null ? null : bicycleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_rental_record.user_id
     *
     * @return the value of bicycle_rental_record.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_rental_record.user_id
     *
     * @param userId the value for bicycle_rental_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_rental_record.start_time
     *
     * @return the value of bicycle_rental_record.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_rental_record.start_time
     *
     * @param startTime the value for bicycle_rental_record.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_rental_record.end_time
     *
     * @return the value of bicycle_rental_record.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_rental_record.end_time
     *
     * @param endTime the value for bicycle_rental_record.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle_rental_record.consumptive_money
     *
     * @return the value of bicycle_rental_record.consumptive_money
     *
     * @mbggenerated
     */
    public Integer getConsumptiveMoney() {
        return consumptiveMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle_rental_record.consumptive_money
     *
     * @param consumptiveMoney the value for bicycle_rental_record.consumptive_money
     *
     * @mbggenerated
     */
    public void setConsumptiveMoney(Integer consumptiveMoney) {
        this.consumptiveMoney = consumptiveMoney;
    }
}