package com.cp.model;

public class HeadPortrait {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column head_portrait.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column head_portrait.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column head_portrait.image_content
     *
     * @mbggenerated
     */
    private byte[] imageContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column head_portrait.id
     *
     * @return the value of head_portrait.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column head_portrait.id
     *
     * @param id the value for head_portrait.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column head_portrait.user_id
     *
     * @return the value of head_portrait.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column head_portrait.user_id
     *
     * @param userId the value for head_portrait.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column head_portrait.image_content
     *
     * @return the value of head_portrait.image_content
     *
     * @mbggenerated
     */
    public byte[] getImageContent() {
        return imageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column head_portrait.image_content
     *
     * @param imageContent the value for head_portrait.image_content
     *
     * @mbggenerated
     */
    public void setImageContent(byte[] imageContent) {
        this.imageContent = imageContent;
    }
}