package com.cp.dao;

import com.cp.model.Faculty;

public interface FacultyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty
     *
     * @mbggenerated
     */
    int insert(Faculty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty
     *
     * @mbggenerated
     */
    int insertSelective(Faculty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty
     *
     * @mbggenerated
     */
    Faculty selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Faculty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Faculty record);
}