package com.cp.model;

public class NoticeDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_detail.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_detail.notice_id
     *
     * @mbggenerated
     */
    private String noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_detail.receiver_id
     *
     * @mbggenerated
     */
    private String receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_detail.is_read
     *
     * @mbggenerated
     */
    private Boolean isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_detail.is_show
     *
     * @mbggenerated
     */
    private Boolean isShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_detail.id
     *
     * @return the value of notice_detail.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_detail.id
     *
     * @param id the value for notice_detail.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_detail.notice_id
     *
     * @return the value of notice_detail.notice_id
     *
     * @mbggenerated
     */
    public String getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_detail.notice_id
     *
     * @param noticeId the value for notice_detail.notice_id
     *
     * @mbggenerated
     */
    public void setNoticeId(String noticeId) {
        this.noticeId = noticeId == null ? null : noticeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_detail.receiver_id
     *
     * @return the value of notice_detail.receiver_id
     *
     * @mbggenerated
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_detail.receiver_id
     *
     * @param receiverId the value for notice_detail.receiver_id
     *
     * @mbggenerated
     */
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId == null ? null : receiverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_detail.is_read
     *
     * @return the value of notice_detail.is_read
     *
     * @mbggenerated
     */
    public Boolean getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_detail.is_read
     *
     * @param isRead the value for notice_detail.is_read
     *
     * @mbggenerated
     */
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_detail.is_show
     *
     * @return the value of notice_detail.is_show
     *
     * @mbggenerated
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_detail.is_show
     *
     * @param isShow the value for notice_detail.is_show
     *
     * @mbggenerated
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }
}